=== milica152/XML_tim27/Backend/src/main/resources/static/schemas/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:u="https://github.com/milica152/XML_tim27"
           targetNamespace="https://github.com/milica152/XML_tim27" elementFormDefault="qualified">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded" minOccurs="0" type="u:TUser"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TUser">
        <xs:sequence>
            <xs:element name="username">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="25"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="password">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="4"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="^[_A-Za-z0-9-+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="profession" type="xs:string"/>
            <xs:element name="myPapers">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="myScientificPaperID"
                                    type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="myReviews">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="myReviewID"
                                    type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="pendingPapersToReview">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="paperToReviewID"
                                    type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="role" type="u:TRole"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TRole">
        <xs:restriction base="xs:string">
            <xs:enumeration value="author"/>
            <xs:enumeration value="editor"/>
            <xs:enumeration value="reviewer"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== milica152/XML_tim27/data/test/test_users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns="https://github.com/milica152/XML_tim27"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/milica152/XML_tim27 file:/C:/Users/mica/Desktop/xml/milica/XML_tim27/schemas/users.xsd">
    <user>
        <username>anci</username>
        <password>$2a$10$W1yQAyeD/Oab5BB155vfSe2kxivlkkG47EKyqHkaHnzbP5VOBp8bK</password>
        <name>Ana</name>
        <surname>Pjevic</surname>
        <email>ana1@gmail.com</email>
        <profession>Doktor</profession>
        <myPapers>
            <myScientificPaperID>dDhtcyKV1dfCV0xMXqg9EnnTV</myScientificPaperID>
            <myScientificPaperID>G0V</myScientificPaperID>
        </myPapers>
        <myReviews>
            <myReviewID>pKEhO-j7yC4U75f_._t</myReviewID>
            <myReviewID>BRH</myReviewID>
        </myReviews>
        <pendingPapersToReview>
            <paperToReviewID>uPUaieJIpv7HbjpiMw</paperToReviewID>
            <paperToReviewID>qzGwRmw_KGcrEEhZgTlEOQGL</paperToReviewID>
        </pendingPapersToReview>
        <role>author</role>
    </user>
    <user>
        <username>ssKMDNEbbGV2fRQbLl9rSC</username>
        <password>D1l9tLy</password>
        <name>bu8ItF-SzHkOZvwAkLFdt_K75o377Yb</name>
        <surname>rSXWPkOlM.VWAKOKta0</surname>
        <email>c@h</email>
        <profession>DrMr</profession>
        <myPapers>
            <myScientificPaperID>IkOJ3MmMvnUXaFLu6r9siKtSV</myScientificPaperID>
            <myScientificPaperID>Wbe4tcgTb4ONQ</myScientificPaperID>
        </myPapers>
        <myReviews>
            <myReviewID>LqIGjL6</myReviewID>
            <myReviewID>F9tj_cu1LVQauA6I1iJ6u5</myReviewID>
        </myReviews>
        <pendingPapersToReview>
            <paperToReviewID>Nx</paperToReviewID>
            <paperToReviewID>j_gG3C</paperToReviewID>
        </pendingPapersToReview>
        <role>reviewer</role>
    </user>
</users>
