=== milica152/XML_tim27/schemas/scientificPaper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:sp="https://www.uns.ac.rs/scientificPaper"
    targetNamespace="https://www.uns.ac.rs/scientificPaper" elementFormDefault="qualified">
    <xs:element name="scientificPaper">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sp:title"/>
                <xs:element name="authors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="sp:author"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="abstract">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="sp:plainChapter"/>
                            <xs:element name="keywords">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" ref="sp:keyword"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="chapters">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="sp:chapter"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="references">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="sp:reference"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="datePublished" type="xs:date"/>
            <xs:attribute name="institution" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TChapter">
        <xs:sequence>
            <xs:element ref="sp:title"/>
            <xs:element name="text">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" ref="sp:paragraph"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute ref="sp:id"/>
    </xs:complexType>
    <xs:element name="chapter">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="sp:TChapter">
                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                        <xs:element ref="sp:image"/>
                        <xs:element ref="sp:list"/>
                        <xs:element ref="sp:table"/>
                        <xs:element name="codeBlock">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute ref="sp:id"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="referencePointer">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute ref="sp:id"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="plainChapter" type="sp:TChapter"/>
    <xs:element name="keyword" type="xs:string"/>
    <xs:element name="paragraph">
        <xs:complexType>
            <xs:sequence/>
            <xs:attribute ref="sp:fontsize"/>
            <xs:attribute ref="sp:id"/>
            <xs:attribute ref="sp:style"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TTitle">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="sp:level"/>
                <xs:attribute ref="sp:fontsize"/>
                <xs:attribute ref="sp:style"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="title" type="sp:TTitle"/>
    <xs:simpleType name="TLevel">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="8"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attribute name="level" type="sp:TLevel"/>
    <xs:simpleType name="TFontSize">
        <xs:restriction base="xs:positiveInteger">
            <xs:maxInclusive value="545"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attribute name="fontsize" type="sp:TFontSize"/>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="style" type="xs:string"/>
    <xs:attribute name="ordinal" type="xs:positiveInteger"/>
    <xs:complexType name="TAuthor">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
            <xs:element minOccurs="0" name="profession" type="xs:string"/>
            <xs:element minOccurs="0" name="contact" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="author">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="sp:TAuthor">
                    <xs:attribute ref="sp:id"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="reference">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="sp:author"/>
                <xs:element minOccurs="0" name="url" type="xs:string"/>
                <xs:element name="referenceName" type="xs:string"/>
            </xs:sequence>
            <xs:attribute ref="sp:id"/>
            <xs:attribute name="year" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="listItem" type="xs:string"/>
            </xs:sequence>
            <xs:attribute ref="sp:id"/>
            <xs:attribute ref="sp:style"/>
            <xs:attribute name="isOrdered" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="row">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="cell">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute ref="sp:style"/>
                                            <xs:attribute ref="sp:ordinal"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute ref="sp:ordinal"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="sp:id"/>
            <xs:attribute name="width" type="xs:positiveInteger"/>
            <xs:attribute name="height" type="xs:positiveInteger"/>
            <xs:attribute name="measuringUnit" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="image">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="concreteImage" type="xs:base64Binary"/>
            </xs:sequence>
            <xs:attribute ref="sp:id"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== milica152/XML_tim27/data/test/generatedScientificPaper3.xml
<?xml version="1.0" encoding="UTF-8"?>
<scientificPaper xmlns="https://github.com/milica152/XML_tim27"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/milica152/XML_tim27 schemas/scientificPaper.xsd" institution="ko4hiSoUyQN">
    <metadata>
        <status>accepted</status>
        <datePublished>2020-09-29Z</datePublished>
        <dateAccepted>2020-11-28</dateAccepted>
        <keywords>
            <keyword>I</keyword>
            <keyword>KTZsealjymwbht4l</keyword>
        </keywords>
    </metadata>
    <title>Q0HNd_4</title>
    <authors>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="vug/ru">
            <name>qBXYF6YbrWVSdolA3-_</name>
            <surname>a5OMP3wFT-</surname>
            <profession>qH2kuqYDZ_e</profession>
            <contact>PtdK9vOce2ZAtVshsMP3W3CXxswrSh</contact>
        </author>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="nn/g">
            <name>CE7emXvfnMvc5</name>
            <surname>o6I_tI</surname>
            <profession>AS2DU</profession>
            <contact>S5Jc3rZtsZNLRnj67</contact>
        </author>
    </authors>
    <abstract>
        <plainChapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="syoc/pxklz/wur/vo/mr">
            <title level="366262141" fontsize="896610096" style="OjiIOn9._T2ICfGT">Hs3JqEq2CbTFy7l1tYqA2oLLXx64LV</title>
            <text>
                <paragraph fontsize="1752524501" sp:id="qg/dlfzt/yfv/rsujj/wwlo" style="PQ">Qkwa22kms1NhebUcl6E7bmz</paragraph>
                <paragraph fontsize="295407291" sp:id="f/xp" style="dpctodlI39LdbghPAptB">YlLc_2zKVYiELMR</paragraph>
            </text>
        </plainChapter>
        <plainChapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="d/i">
            <title level="1880002945" fontsize="481197230" style="hZDvSaSnfjhUVe1UuA">e4iAu30n6l_jf3kiwwu0y</title>
            <text>
                <paragraph fontsize="1358830038" sp:id="ltwr/c" style="Kch">Rcw_X8.bUzBKzeL9N2u-Wje</paragraph>
                <paragraph fontsize="399365471" sp:id="du/nn/nr/u" style="R-d1c9647mU2EyrONr">dbkj.G.pX1</paragraph>
            </text>
        </plainChapter>
    </abstract>
    <chapters>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="d/pay">
            <title level="1595258764" fontsize="649918079" style="v0igRdw6.jLx5ePc1Ttw">J9</title>
            <text>
                <paragraph fontsize="366950184" sp:id="n/fqls" style="mmW.7.2K3">G</paragraph>
                <paragraph fontsize="13189870" sp:id="j/gtj/tnuhc/pvz/p" style="k1zIrGw5w68.u5SsU-1z._RJC">i3hJQ92vuHbhIc3Pvs9ypSJo</paragraph>
            </text>
            <codeBlock sp:id="ptm/za">kwj-ZSkzX</codeBlock>
            <codeBlock sp:id="q/esqgb/sb/pddu">s6_QdsLRDKbHtE1BrJw89W.2Boe</codeBlock>
        </chapter>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="ybb/an/vv/ffqtgql/uvqj">
            <title level="1471830779" fontsize="1820272237" style="DWj0ljw">gHu-_Fc</title>
            <text>
                <paragraph fontsize="1936930895" sp:id="xln/zs/rhmlp/cq/pm" style="pbMLGB_408q-t7rIeJ">Q8XEL7</paragraph>
                <paragraph fontsize="2027159805" sp:id="n/puzu" style="tzTKoUXq6v">cW0cfl49_4_</paragraph>
            </text>
            <referencePointer sp:id="e/llta/bqw">CBQDyjWcDaCbq7KjlvUDb</referencePointer>
            <image sp:id="u/u">
                <description>A5wE-5NMY</description>
                <concreteImage>76777580896978878866738177817069878883678877807067858176736672658072868668717287826889718187688071876778</concreteImage>
            </image>
        </chapter>
    </chapters>
    <references>
        <reference xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="ri/z" year="2021-08-01" authorName="giS_YPJX9McVY4D-Rx">
            <url>mgat</url>
            <name>Ynzl52w.6</name>
        </reference>
    </references>
</scientificPaper>

=== milica152/XML_tim27/data/test/SPinstance2.xml
<?xml version="1.0" encoding="UTF-8"?>
<scientificPaper xmlns="https://github.com/milica152/XML_tim27"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/milica152/XML_tim27 file:/C:/Users/mica/Desktop/xml/milica/XML_tim27/schemas/scientificPaper.xsd" institution="A7fJj">
    <metadata>
        <datePublished>2021-02-21</datePublished>
        <dateAccepted>2020-04-11Z</dateAccepted>
        <keywords>
            <keyword>DpFdPI5_ZjBO5z.vCOLquCb0rVR</keyword>
            <keyword>H7aU</keyword>
        </keywords>
    </metadata>
    <title>Vtl1fAtMpBwLmC2xXFzDl4zf3V</title>
    <authors>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="y/nxah">
            <name>Lnt-LtI4maXa6qDgBVr7</name>
            <surname>RyUsg7h879LBYZGmJ</surname>
            <profession>WP8pUe_5Kbq4ZNwQfPi9psYgweL</profession>
            <contact>JngVYbGRVU-QN3bbuaRJJDH</contact>
        </author>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="pdm/eukbu/l">
            <name>K</name>
            <surname>j</surname>
            <profession>x1CkUo40L1LmBb</profession>
            <contact>g1yLi0s8_G4KrMdn</contact>
        </author>
    </authors>
    <abstract>
        <plainChapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="yj/ae/ojv">
            <title level="820868349" fontsize="1937570622" style="F">GLrPwtUYRFcnfYLwm3MNOuBAVuT.1</title>
            <text>
                <paragraph fontsize="1405303253" sp:id="y/nhh" style="FBf7SkAMZVKN1B0GSvkL.N_bzJQY4">Kpl-B7J4SFPiS0bh</paragraph>
                <paragraph fontsize="676798426" sp:id="i/lm/ge/hmd" style="zxbdN.3zSfz95P1A5Sp74tk0">yGnQ0hc6Kvmt39tDugjCkY_rdab</paragraph>
            </text>
        </plainChapter>
        <plainChapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="j/th">
            <title level="1144129006" fontsize="302009387" style="fyElKKGfNb">YcYnE1NZ2XSdMyqCO-</title>
            <text>
                <paragraph fontsize="941359764" sp:id="m/u" style="C2Qp1wlwMNEp4QX9u2j0FxzerR18q">De1T73nffpTZoNE-</paragraph>
                <paragraph fontsize="1070618682" sp:id="r/sz/wl/y" style="_E1vW0yoflJnVPfLBdBq2DBjFd55xc">P8</paragraph>
            </text>
        </plainChapter>
    </abstract>
    <chapters>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="b/ekbq">
            <title level="697997016" fontsize="203694469" style="Xc0DpJTo">ilmpYYHXvsudJgypffH_</title>
            <text>
                <paragraph fontsize="791671483" sp:id="jxsq/km/bm/nzda" style="c1gUXh">qd0NJfiHXLfcRDlkXZH7BaSoqQhLqx</paragraph>
                <paragraph fontsize="767224137" sp:id="q/whdp/td/jqieq/r" style="CgAV.oR">lbz5</paragraph>
            </text>
            <codeBlock sp:id="qufm/xua">WAKZ0h1nJccHfe3KoLevtg</codeBlock>
            <referencePointer sp:id="p/kdxhz/ik/tibxc/gifw">NknoPWV.eTzqeJ_qTAv</referencePointer>
        </chapter>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="s/feq">
            <title level="2047444639" fontsize="892071150" style="cpIF5MLHw.7nf2lxxEwr9wCMXq">SsA9cuIE-GWd</title>
            <text>
                <paragraph fontsize="2118747350" sp:id="ohm/sp/t" style="m.mfFa">kkflFMUa7vjQjk</paragraph>
                <paragraph fontsize="232804275" sp:id="qkar/y" style="BliLB9fMVKfZ-87XtPZ6pRoWNOWLpe">rsl4HdHLxQYHcn</paragraph>
            </text>
            <table sp:id="y/l" width="233517969" height="1617135835" measuringUnit="gqE5k">
                <row ordinal="1225310860">
                    <cell style="LUvO-eVniDB_-q" ordinal="1452057127">R9T54FqiwqLODQB-yFQ9o8iJfKhZ</cell>
                    <cell style="pLt8" ordinal="1781743024">VrbToHddVo_-oEpkxFcfwn</cell>
                </row>
                <row ordinal="1794178009">
                    <cell style="FsBA-dKb_A9TZScooguhap" ordinal="1196596486">q24ymK8kt74.</cell>
                    <cell style="EV2c0sRYZmGY_O" ordinal="339090690">mtW5Z9OXuw9YsD</cell>
                </row>
            </table>
            <list sp:id="fnu/laaj" style="hiEX71VzaOq2t" isOrdered="false">
                <listItem>ND4ZW9FS</listItem>
                <listItem>i57qZCobRpH3RUjcrLH9uBkAeA9bI</listItem>
            </list>
        </chapter>
    </chapters>
    <references>
        <reference xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="c/wch/k" year="2020-03-28Z" authorName="IRXQ8eGseqs6FxtappSouXxE">
            <url>_p</url>
            <name>UoKkw7SoGQRdaq7kMFxY72</name>
        </reference>
    </references>
</scientificPaper>

=== milica152/XML_tim27/data/test/generatedScientificPaper1.xml
<?xml version="1.0" encoding="UTF-8"?>
<scientificPaper xmlns="https://github.com/milica152/XML_tim27"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/milica152/XML_tim27 file:/D:/Faks/VII%20semestar%20-%20XML/XML-Projekat/schemas/scientificPaper.xsd" institution="w">
    <metadata>
        <status>in process</status>
        <datePublished>2022-01-30Z</datePublished>
        <dateAccepted>2021-02-23Z</dateAccepted>
        <keywords>
            <keyword>HaU17</keyword>
            <keyword>_9cifY9tYTH8THEw</keyword>
        </keywords>
    </metadata>
    <title>zgdhpPLxp</title>
    <authors>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="q/whdp/td/jqieq/r">
            <name>l.wqXnqNZHPCAXkfEtFLY8dX-</name>
            <surname>MSCCMpKe2q4rI</surname>
            <profession>dtxlqF9L-k2</profession>
            <contact>iA0Hzj-EA9HwsPhPvsCE3vltMzvIHN</contact>
        </author>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="qufm/xua">
            <name>_gh</name>
            <surname>ppYtEG2izIFhPQe49o_fdG7RUUuR2</surname>
            <profession>JTZNez1qZSbiObOpwaDc4MAj</profession>
            <contact>LB3rBM0oweTtuc</contact>
        </author>
    </authors>
    <abstract>
        <plainChapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="p/kdxhz/ik/tibxc/gifw">
            <title level="1702007707" fontsize="1853674457" style="ieoseLjrsSyYO1wdcJLEU0ELGbLbSL">JeZv.fY1WMQ0M</title>
            <text>
                <paragraph fontsize="553171423" sp:id="s/feq" style="IMa">WYrdu</paragraph>
                <paragraph fontsize="2139994758" sp:id="ohm/sp/t" style="ikP7.Wzv9Sug7vN">Z1Y</paragraph>
            </text>
        </plainChapter>
        <plainChapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="qkar/y">
            <title level="1563714438" fontsize="359839494" style="fHuPYTOUv.0p">pM_wXfA2U4aYkE3l9EZsJbcmr</title>
            <text>
                <paragraph fontsize="1627198674" sp:id="y/l" style="OPt7JULC7Abis3VAqp1Gz">E</paragraph>
                <paragraph fontsize="26112268" sp:id="fnu/laaj" style="L.c">L_vvUd0BbbrGA2rmgXdR</paragraph>
            </text>
        </plainChapter>
    </abstract>
    <chapters>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="c/wch/k">
            <title level="1458799565" fontsize="1211082384" style="Qdbas2ouM96UXO">r9F</title>
            <text>
                <paragraph fontsize="575697556" sp:id="s/ri/voc/uifse/asby" style="EAgX6X2hN8oRN4myhdrg6uDN_-">PR-U_.CNfxN3</paragraph>
                <paragraph fontsize="90698896" sp:id="t/d" style="j.LgtvxITEVYoSs7KrexEhkZ">g7vmM2gCIoS7OusAkqDBkG3A3VhwSF</paragraph>
            </text>
            <table sp:id="w/jm/rq/ut/t" width="896617139" height="1518397859" measuringUnit="o_7G3Q0vNW4KciV28ilN8Xw">
                <row ordinal="1471033180">
                    <cell style="CrwB" ordinal="1598001508">O9CMkBjHcfV8A983yyW</cell>
                    <cell style="HucAfsV.0bcKR" ordinal="605328138">ijNpLRUTyvSB.wuoObXoFlHjH2A.c</cell>
                </row>
                <row ordinal="406414052">
                    <cell style="L4z" ordinal="1341434682">pDsmnuvLdZhvXH68_mXSJKLbe-</cell>
                    <cell style="eGANWE.ijJuP6IlST_-hdwQTUz-Q" ordinal="508735066">nb23r</cell>
                </row>
            </table>
            <codeBlock sp:id="x/xih">OqJVPOJw</codeBlock>
        </chapter>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="k/p">
            <title level="1310139924" fontsize="2114055809" style="m_RPBnjgp">Idf</title>
            <text>
                <paragraph fontsize="485978431" sp:id="e/o" style="LBhWPtJaihrikL1h1">U90NNco__0rz5nKaWZ</paragraph>
                <paragraph fontsize="2147420407" sp:id="ca/c" style="QfaeHhChqBKrmuUm5h7Tm5BT">WkubibOJnsGLVWqbVIk-y6_qk</paragraph>
            </text>
            <referencePointer sp:id="ap/kw">eW3C1jwQtoTy49AO..</referencePointer>
            <list sp:id="m/n" style="mt055baXy9U1Ac6o1rXy" isOrdered="1">
                <listItem>sA1F8V_EbiijP6FIYC.</listItem>
                <listItem>U-1iJ2WVJT2d</listItem>
            </list>
        </chapter>
    </chapters>
    <references>
        <reference xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="bvbt/v" year="2020-04-17Z" authorName="Go_8">
            <url>KgAwcJi7Y-c_eVnOW0FJDLCH</url>
            <name>Dg8vk3DpUZnoE7qYfCH.</name>
        </reference>
    </references>
</scientificPaper>
