=== milica152/XML_tim27/schemas/scientificPaper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:sp="https://www.uns.ac.rs/scientificPaper"
    targetNamespace="https://www.uns.ac.rs/scientificPaper" elementFormDefault="qualified">
    <xs:element name="scientificPaper">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sp:title"/>
                <xs:element name="authors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="sp:author"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="abstract">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="sp:plainChapter"/>
                            <xs:element name="keywords">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" ref="sp:keyword"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="chapters">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="sp:chapter"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="references">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="sp:reference"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="datePublished" type="xs:date"/>
            <xs:attribute name="institution" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TChapter">
        <xs:sequence>
            <xs:element ref="sp:title"/>
            <xs:element name="text">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" ref="sp:paragraph"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute ref="sp:id"/>
    </xs:complexType>
    <xs:element name="chapter">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="sp:TChapter">
                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                        <xs:element ref="sp:image"/>
                        <xs:element ref="sp:list"/>
                        <xs:element ref="sp:table"/>
                        <xs:element name="codeBlock">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute ref="sp:id"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="referencePointer">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute ref="sp:id"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="plainChapter" type="sp:TChapter"/>
    <xs:element name="keyword" type="xs:string"/>
    <xs:element name="paragraph">
        <xs:complexType>
            <xs:sequence/>
            <xs:attribute ref="sp:fontsize"/>
            <xs:attribute ref="sp:id"/>
            <xs:attribute ref="sp:style"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TTitle">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="sp:level"/>
                <xs:attribute ref="sp:fontsize"/>
                <xs:attribute ref="sp:style"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="title" type="sp:TTitle"/>
    <xs:simpleType name="TLevel">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="8"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attribute name="level" type="sp:TLevel"/>
    <xs:simpleType name="TFontSize">
        <xs:restriction base="xs:positiveInteger">
            <xs:maxInclusive value="545"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attribute name="fontsize" type="sp:TFontSize"/>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="style" type="xs:string"/>
    <xs:attribute name="ordinal" type="xs:positiveInteger"/>
    <xs:complexType name="TAuthor">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
            <xs:element minOccurs="0" name="profession" type="xs:string"/>
            <xs:element minOccurs="0" name="contact" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="author">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="sp:TAuthor">
                    <xs:attribute ref="sp:id"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="reference">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="sp:author"/>
                <xs:element minOccurs="0" name="url" type="xs:string"/>
                <xs:element name="referenceName" type="xs:string"/>
            </xs:sequence>
            <xs:attribute ref="sp:id"/>
            <xs:attribute name="year" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="listItem" type="xs:string"/>
            </xs:sequence>
            <xs:attribute ref="sp:id"/>
            <xs:attribute ref="sp:style"/>
            <xs:attribute name="isOrdered" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="row">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="cell">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute ref="sp:style"/>
                                            <xs:attribute ref="sp:ordinal"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute ref="sp:ordinal"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="sp:id"/>
            <xs:attribute name="width" type="xs:positiveInteger"/>
            <xs:attribute name="height" type="xs:positiveInteger"/>
            <xs:attribute name="measuringUnit" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="image">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="concreteImage" type="xs:base64Binary"/>
            </xs:sequence>
            <xs:attribute ref="sp:id"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== milica152/XML_tim27/data/test/generatedScientificPaper2.xml
<?xml version="1.0" encoding="UTF-8"?>
<scientificPaper xmlns="https://github.com/milica152/XML_tim27"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/milica152/XML_tim27 file:/D:/Faks/VII%20semestar%20-%20XML/XML-Projekat/schemas/scientificPaper.xsd" institution="_iK">
    <metadata>
        <keywords>
            <keyword>MIOiBffSqF</keyword>
            <keyword>lCn8Ho</keyword>
        </keywords>
    </metadata>
    <title>g.MNRXfgxtmFfMuUfWUQ15</title>
    <authors>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="s/jye/pcb/pwki/zn">
            <name>SDdNkyAaZLeXeExYCAeUjgxAIbk05</name>
            <surname>pikExE</surname>
            <profession>mF9nwysyp4DMJIWj8.eIrCde</profession>
            <contact>aSnv03Xl2o2qo4</contact>
        </author>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="n/sj">
            <name>dNIQ0Q</name>
            <surname>YzF_ij9</surname>
            <profession>FCo2</profession>
            <contact>TzhNd2aIJo3BU8P1-nrRB16s6n</contact>
        </author>
    </authors>
    <abstract>
        <paragraph xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="clnk/t" style="d3">paanOB74fYN.Uf</paragraph>
        <paragraph xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="sa/m" style="NBp2j">Tsfv0OetWSRoTMGX1</paragraph>
    </abstract>
    <chapters>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="u/t">
            <title level="3" style="BNsp0UiFtKkv03XkE3">mR</title>
            <text>
                <paragraph sp:id="e/uj/tyqt/kz/xr" style="hmGwNOp468Z33xl1gtWxk">YV</paragraph>
                <paragraph sp:id="q/go" style="NJh0jr5d-">hElLgmGu1iMkfEhbi</paragraph>
            </text>
<!--            <image sp:id="z/vh">
                <description>ttZPY0-vnjmuVMqWv</description>
                <concreteImage>7283838367666887857977717082857484808588</concreteImage>
            </image>-->
<!--            <list sp:id="t/dy/unpglb/gaiiz/hh" style="OKyqeAOBQlfFr0v1L" isOrdered="1">
                <listItem>dgE8G.9a6NwFIQPlDls84T.iaoG9d</listItem>
                <listItem>qb</listItem>
            </list>-->
<!--            <table sp:id="lq/fcfn/ksy" width="425" height="413" measuringUnit="mm">
                <row>
                    <cell style="Et8sKyKFEh">sgcJ_wrvoLFjRlNdD48.tPlx.T</cell>
                    <cell style="EhUBM7qIA2SDVIUrheU">vIdhHy5LySIhx.6</cell>
                </row>
                <row>
                    <cell style="H6VRnpkrNDr.1VKal">eEHOGt0mNeSsLO</cell>
                    <cell style="Qyep3EzH">byObK8roI1I</cell>
                </row>
            </table>-->
            <codeBlock sp:id="e/d">jnxI6PvKVx4jX.3osRR45ZH</codeBlock>
<!--            <referencePointer sp:id="cudp/kuu/kx/xhelhdgd/z">sgk1WFvUyTNNVhNpKWThwb</referencePointer>-->
<!--            <image sp:id="a/tacxicy/ownzdeb/je/l">
                <description>prHjrNVa</description>
                <concreteImage>7381836674797579789083826875857384836779</concreteImage>
            </image>-->
            <list sp:id="y/wpc" style="c" isOrdered="1">
                <listItem>g.</listItem>
                <listItem>LGNYCdQ1XMRgGg_fLDuJ</listItem>
            </list>
<!--            <table sp:id="a/wtnwu/cfb/mq/z" width="72" height="844" measuringUnit="cm">
                <row>
                    <cell style="t_N269vpTY">pHhTSDgjtzbffFp8_</cell>
                    <cell style="KtRbjAp2BQpAPAKotE4e12VHTU">Eb4rNzI60fbuXug</cell>
                </row>
                <row>
                    <cell style="JqJevp_OrMR">eAXy2Ew0</cell>
                    <cell style="QwsNxbe5">ZZw</cell>
                </row>
            </table>-->
<!--            <codeBlock sp:id="wd/x">lxDgqXRfF2jR7m34A.Dw6SY</codeBlock>-->
<!--            <referencePointer sp:id="k/c">tqj9CaJaXPrrC_W9</referencePointer>-->
        </chapter>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="m/w">
            <title level="4" style="i9lyF_5JC9a.la">ie_UwowVrmuAVmg.94EJvmVo2POU6k</title>
            <text>
                <paragraph sp:id="t/x" style="wkJQuOrm40wX7Lj">p3</paragraph>
                <paragraph sp:id="w/m" style="ksCodZqpNzb.SF2Ax0T0mi2pm">jAYHDpW36Yd3Osg-nv1wZA</paragraph>
            </text>
<!--            <image sp:id="t/sbp">
                <description>MvItpXln0ye6EX6ZLN7Q_Oi_xRk</description>
                <concreteImage>7565668879697767858365897570706689858884797288888782806975797276</concreteImage>
            </image>-->
<!--            <list sp:id="foz/raq/se/xn/e" style="rReCMIeai1moTSb4GS-YDG1" isOrdered="1">
                <listItem>VNp1TGV5Bmo2</listItem>
                <listItem>mkxREVZcWJ6iqy59NaGzGK9SdaN</listItem>
            </list>-->
            <table sp:id="l/zuk/xj" width="531" height="476" measuringUnit="px">
                <row>
                    <cell style="_fFqZOiipQ8t1yo-AFN9z2JGY">fwa</cell>
                    <cell style="QWAUyvt3oArvr9qhi0C5uj-MRe7x">ehRFcM6rQAh_hu2Yb8vD63hZdc8xV</cell>
                </row>
                <row>
                    <cell style="BjQDru7z-l0g">rFglA0eyIU1J6QUD</cell>
                    <cell style="b-9i31lX0i9n">h.WG8E_Q7Nsru1Mz989.Mb22ubld</cell>
                </row>
            </table>
<!--            <codeBlock sp:id="xlmd/xlbb">X5k5N_tb18OWh</codeBlock>-->
<!--            <referencePointer sp:id="l/knfi/p">hOLHvvWU4</referencePointer>-->
<!--            <image sp:id="n/ainq">
                <description>LXMTwIklvn2g</description>
                <concreteImage>7989888670786788</concreteImage>
            </image>-->
<!--            <list sp:id="aad/dnaz/fs/fs/e" style="sSb8g8DJuUYy6PA7qQA" isOrdered="0">
                <listItem>beH5NYPMeiHLT4BDKKIlNM</listItem>
                <listItem>SzU</listItem>
            </list>-->
            <table sp:id="c/a" width="727" height="852" measuringUnit="cm">
                <row>
                    <cell style="h">ix6skPoY89z2QdTKaLUmhjmfA0Vat</cell>
                    <cell style="nDz.vy">bn</cell>
                </row>
                <row>
                    <cell style="WOH">iAaFkTtJz</cell>
                    <cell style="rPEEc7laxFkjjWt24rM9MzmS3W">gptwaTkJhZB</cell>
                </row>
            </table>
<!--            <codeBlock sp:id="ln/r">vanaKpJJzo0H9FRoOgZT</codeBlock>-->
<!--            <referencePointer sp:id="s/i">vOnJh-YmEpF-Dyl0iucIMQF_</referencePointer>-->
        </chapter>
    </chapters>
    <references>
        <reference xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="g/s">
            <url>igoqN_CFSD</url>
            <name>BN7Yy2LQ-Tb6x-Hmm99UZYtP.ve8</name>
            <year>uCddQLc34aj3XyuaT2JzqJ7</year>
            <authorName>KblgSXP.magUW8M2AaxA</authorName>
        </reference>
    </references>
</scientificPaper>

=== milica152/XML_tim27/data/test/SPinstance3.xml
<?xml version="1.0" encoding="UTF-8"?>
<scientificPaper xmlns="https://github.com/milica152/XML_tim27"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/milica152/XML_tim27 file:/C:/Users/mica/Desktop/xml/milica/XML_tim27/schemas/scientificPaper.xsd" institution="DcqEMbJkLlWjSIpvt.qq">
    <metadata>
        <datePublished>2020-05-16Z</datePublished>
        <dateAccepted>2020-12-01Z</dateAccepted>
        <keywords>
            <keyword>JJb</keyword>
            <keyword>WQZ</keyword>
        </keywords>
    </metadata>
    <title>nXh9nJOB7HfU569K</title>
    <authors>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="s/ri/voc/uifse/asby">
            <name>uF</name>
            <surname>tfs</surname>
            <profession>hdrWTAFKHNXEk_7G_mtzVLR8</profession>
            <contact>G</contact>
        </author>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="t/d">
            <name>f5ErDkG7</name>
            <surname>GpKhaAw4bGzsVouZp</surname>
            <profession>_cglBdHcTaNjkT8NSdiw_Vx3mL</profession>
            <contact>AI3TtK</contact>
        </author>
    </authors>
    <abstract>
        <plainChapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="w/jm/rq/ut/t">
            <title level="2041882251" fontsize="18149426" style="Ie7r-TC_s">LvidDMv-_NHs7.D</title>
            <text>
                <paragraph fontsize="1870715540" sp:id="x/xih" style="DOyDtzV4dj">oWoUobdSR0V5hApSIx</paragraph>
                <paragraph fontsize="956514933" sp:id="k/p" style="LP9ZEaYfpatqySX">aJYucXSddXW7khGwZN-5ZhcPDn9N9q</paragraph>
            </text>
        </plainChapter>
        <plainChapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="e/o">
            <title level="1009589659" fontsize="1233669770" style="GBBAWK5rFkZmqU">iCdJq0Ovmb</title>
            <text>
                <paragraph fontsize="916933852" sp:id="ca/c" style="wUvf74sIkUkgLG04_JpJkAcKY">T46Kzx5mSDcidBEEoew</paragraph>
                <paragraph fontsize="871003355" sp:id="ap/kw" style="ukz-1jtSZgDAJ_M.lv9">tQMtFk0ymjs</paragraph>
            </text>
        </plainChapter>
    </abstract>
    <chapters>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="m/n">
            <title level="824973156" fontsize="861778521" style="nx8cjD9kOOgJvm5SKHslRoKZQT">Q6om6m4LfL</title>
            <text>
                <paragraph fontsize="753339711" sp:id="bvbt/v" style="Qbdlvc">Bu69Q.a4VoJbjzI9</paragraph>
                <paragraph fontsize="391360002" sp:id="x/k" style="R-">PDjMcrqP2HJW5k</paragraph>
            </text>
            <list sp:id="ni/m" style="UtzWfsI4p9kt_CB_-rcyQj5s" isOrdered="false">
                <listItem>WJV</listItem>
                <listItem>ftIPpvx5iZhQl4</listItem>
            </list>
            <list sp:id="c/t" style="lktCw-NIeWVp-" isOrdered="true">
                <listItem>mOBuPBMRPp</listItem>
                <listItem>pnOBqroTQ-_pJIw</listItem>
            </list>
        </chapter>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="r/m">
            <title level="2071899257" fontsize="1455240584" style="n7">d6_Fh_emu8sZezqqybcGv-0feL</title>
            <text>
                <paragraph fontsize="398947268" sp:id="wq/zqi/qndb/pmzcn/n" style="H4">YGNqwSQ6E1</paragraph>
                <paragraph fontsize="1756547112" sp:id="p/w" style="E33KTDW8WI1vwGNsAWQOf6J4_EOd6S">RlMBtaRF</paragraph>
            </text>
            <referencePointer sp:id="wo/el">hL</referencePointer>
            <table sp:id="q/i" width="662878250" height="198270980" measuringUnit="GL2ZVPa7FWky">
                <row ordinal="1895410277">
                    <cell style="X87Uh0USam0OxgjgheYajW0" ordinal="163877931">tcLjE6g</cell>
                    <cell style="hTZCyplchQgtggywFL7lwa" ordinal="760109051">iN6qfJoKvlbNe.VuuRM01O</cell>
                </row>
                <row ordinal="44031221">
                    <cell style="Egs48gFZUUhXsZLYnvNq7RIXMt0T" ordinal="1756744610">xI4vg</cell>
                    <cell style="a_Noj1G3hdvgrMtQN" ordinal="337648673">yMlFBuk</cell>
                </row>
            </table>
        </chapter>
    </chapters>
    <references>
        <reference xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="e/zkho" year="2021-09-16" authorName="ir0ci38">
            <url>zTK</url>
            <name>Ax5a</name>
        </reference>
    </references>
</scientificPaper>

=== milica152/XML_tim27/data/test/SPinstance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<scientificPaper xmlns="https://github.com/milica152/XML_tim27"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/milica152/XML_tim27 file:/C:/Users/mica/Desktop/xml/milica/XML_tim27/schemas/scientificPaper.xsd" institution="KxgXTT-Z5vZ1eftKO">
    <metadata>
        <keywords>
            <keyword>oioh2otxuOjM</keyword>
            <keyword>lK</keyword>
        </keywords>
    </metadata>
    <title>NuXh0EMLb33vjtO4yVd8fFj2TDy</title>
    <authors>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="guq/rcul/ki">
            <name>ty.h</name>
            <surname>F6QG4bV0xQM</surname>
            <profession>o5i9vHx</profession>
            <contact>vRpMMgj</contact>
        </author>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="jjt/gpuak/f">
            <name>VfmdzN5tmWgSoXnPr8JgWVneAtgYe</name>
            <surname>eG3</surname>
            <profession>hSv_-S2F_nWWn</profession>
            <contact>BqIjlxHA</contact>
        </author>
    </authors>
    <abstract>
        <plainChapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="hu/x">
            <title level="708811506" fontsize="1051896973" style="aVsmL8ka5XnjI-vHP.d">zGOzK8-jwVtKUY</title>
            <text>
                <paragraph fontsize="998904290" sp:id="t/z" style="FjZJAU.AurGz2u12">WdFDyyn4OmA</paragraph>
                <paragraph fontsize="1852301676" sp:id="jntl/dnf" style="Gbk3UYDMJ">mnW7vwf6xjs6Ij-</paragraph>
            </text>
        </plainChapter>
        <plainChapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="n/fysne/cp/eb/w">
            <title level="1195654598" fontsize="535223194" style="YSeEpx-Wr">i8fYI_HEDrVJA-_jlj6FM3JdxA</title>
            <text>
                <paragraph fontsize="1884325342" sp:id="q/srhoa/u" style="xxHskJjVR91FmVso5j1Um">FpjKqJr</paragraph>
                <paragraph fontsize="1960281173" sp:id="u/xp/pzl/i" style="IOrSk">zP_at6tMBN2ScrMuQt2IUgZe7Ms</paragraph>
            </text>
        </plainChapter>
    </abstract>
    <chapters>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="qzl/bsd/ca/n">
            <title level="844603392" fontsize="118105592" style="G">f</title>
            <text>
                <paragraph fontsize="141717254" sp:id="r/cq" style="Ds6JHu.i26wzvfqZ">_tyjdRdEiIX0WKmj</paragraph>
                <paragraph fontsize="54876669" sp:id="k/va/ohsb/f" style="gL41HehC8VbIZ7_bFDZ09YkVwQ">W2CUIM</paragraph>
            </text>
            <codeBlock sp:id="uf/j">fA3Sz4Rvy</codeBlock>
            <referencePointer sp:id="rgvx/wntx/qpy">ieLcHUXDRvQpFUyjA-ZFA</referencePointer>
        </chapter>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="k/kvn">
            <title level="1676332162" fontsize="1136269292" style="PiT30IOMsb2De">jaDZaBNOPIQX8xsLO0Pcoq-sCylX-</title>
            <text>
                <paragraph fontsize="286056003" sp:id="mru/z" style="z5ifYQM">JIm2Y7i3wns3c</paragraph>
                <paragraph fontsize="2140513366" sp:id="x/xnk" style="ni8hlIiVN">WqwgusFmfu_0s</paragraph>
            </text>
            <table sp:id="a/v" width="426719840" height="1709861058" measuringUnit="R5UBc.YnGFsf1LuoqMltaPhKGUjJ">
                <row ordinal="174294027">
                    <cell style="xSq2LcmuMB" ordinal="1875535299">fdf91FSgTxAOaXtEXv0.Lj.j54eyUl</cell>
                    <cell style="OADkqpEVx79V.Szmy" ordinal="1327598681">o6cUsV</cell>
                </row>
                <row ordinal="572568784">
                    <cell style="CLvQft-GGE0" ordinal="548266359">o_43MwuVm_HI4q6R</cell>
                    <cell style="uUDSh4XVAck0w6gIKjYoSlRq_LDZv" ordinal="970507996">vf-2.3pu</cell>
                </row>
            </table>
            <codeBlock sp:id="p/cf">oqwfwVOV</codeBlock>
        </chapter>
    </chapters>
    <references>
        <reference xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="j/nd/ukg" year="2020-09-13Z" authorName="rHmaaqKZCqnDv.t">
            <url>prtfNwM3.2X81.wFcT5U</url>
            <name>Dde7bT156HUZMmWQYkPjrTC</name>
        </reference>
    </references>
</scientificPaper>

=== milica152/XML_tim27/data/test/test_paper.xml
<?xml version="1.0" encoding="UTF-8"?>
<scientificPaper xmlns="https://github.com/milica152/XML_tim27"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/milica152/XML_tim27 file:/C:/Users/mica/Desktop/xml/milica/XML_tim27/schemas/scientificPaper.xsd" datePublished="2020-11-13" institution="g.XbvBA5xu">
    <title level="1890482457" fontsize="1278296186" style="IMHfVFKH3B6btC">K</title>
    <authors>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="ID001">
            <name>exLT0bOPHp.Sa2LEaMrWWHybu0Yp1</name>
            <surname>LXAQqmqIB</surname>
            <profession>euadrAvoPNB</profession>
            <contact>F-pgP1KMCbAwpfFzS9ZPLAYZE91jNj</contact>
        </author>
        <author xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="ID003">
            <name>w1cKxav.T1BeHwJZRRWKmohE</name>
            <surname>yLNo8</surname>
            <profession>CPkJJRNm2AWimiP6rvBtD</profession>
            <contact>Wxfr7eDCJy6y1NpMwhKnmjhIi</contact>
        </author>
    </authors>
    <abstract>
        <plainChapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="ID005">
            <title level="1749186857" fontsize="830242032" style="tf57UofQicZ5NuzvdSENqyJfc.Q">kU2Hrdp</title>
            <text>
                <paragraph fontsize="688654653" sp:id="ID007" style="sXwdyV">d</paragraph>
                <paragraph fontsize="1202099488" sp:id="ID009" style="oS_dAh-yvVMRdGqgjhBIB0w">Behds</paragraph>
            </text>
        </plainChapter>
        <plainChapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="ID011">
            <title level="988428659" fontsize="293716115" style="B">ZWES</title>
            <text>
                <paragraph fontsize="1845656999" sp:id="ID013" style="WuU4K">gjbbNbvfjP7K6FuxnanZpWjJu</paragraph>
                <paragraph fontsize="657852806" sp:id="ID015" style="DVnvtHl-">ayQHbGZRA</paragraph>
            </text>
        </plainChapter>
        <keywords>
            <keyword>bU_GxcA_U</keyword>
            <keyword>y24W8cmDLTQ-Hei-X</keyword>
        </keywords>
    </abstract>
    <chapters>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="ID017">
            <title level="2145917462" fontsize="448001037" style="OerjQ7Flr">gIio2HJYW-jmISlVou</title>
            <text>
                <paragraph fontsize="572252667" sp:id="ID019" style="G7kvziJp8Z9">b6p1nodMqB</paragraph>
                <paragraph fontsize="728034764" sp:id="ID021" style="W8QDr8dZ.4iFO0tKlG8">wDKREmYuoJq2L3x1TS</paragraph>
            </text>
            <list sp:id="ID023" style="eBKO_D" isOrdered="1">
                <listItem>H</listItem>
                <listItem>ceQcfBFv-rDbVwo</listItem>
            </list>
            <codeBlock sp:id="ID025">U93ykghNVTVBqILA</codeBlock>
        </chapter>
        <chapter xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="ID027">
            <title level="1749150648" fontsize="2063691235" style="XU">H7tR2PIGZbfsIs</title>
            <text>
                <paragraph fontsize="313362599" sp:id="ID029" style="wX3UzW.YI7R7g8UbLJ">VOW5O0OkGDuLWrpMpHJ4</paragraph>
                <paragraph fontsize="2110789472" sp:id="ID031" style="IewbsV">VAY</paragraph>
            </text>
            <list sp:id="ID033" style="bkbiDly" isOrdered="true">
                <listItem>f7iB8rI7gKJiC.A88hIswF.ScH</listItem>
                <listItem>Yznm</listItem>
            </list>
            <image sp:id="ID035">
                <description>kJ1Ab</description>
                <concreteImage>65877970697279788575728881788985</concreteImage>
            </image>
        </chapter>
    </chapters>
    <references>
        <reference xmlns:sp="https://github.com/milica152/XML_tim27" sp:id="ID037" year="2020-06-29" authorName="ZyjKd-SV8">
            <url>fYwmsVwyf</url>
            <name>EXP</name>
        </reference>
    </references>
</scientificPaper>
